### ISSUE TITLE
Save state problem

### ISSUE THREAD

**Issue by Collosalhavoc** [citra-emu/citra-android#199]
After the new citra update which introduced save state to users,
I went on to try it
Whenever I try to click on save state the game crashes and I am returned to my game menu
In short I **cannot use the save states**  and we all know the prime importance of save States in video games

**Comment by usernamaewa** [comment]
I have the same problem in save/load, BUT only when I'm doing heavy multitasking, so my phone was starved for RAM, its sd845 6GB. Also maybe because of that, the phone or cpu is super busy so it's slow and causing save/load state to crash citra.

Disabling texture filter and playing at lower resolution help, also maybe citra and at most 1 or 2 apps only at the same time will helps.

**Comment by usernamaewa** [comment]
So maybe the sort term fix right now is make sure your phone is fast and has plenty of ram.

**Comment by luckywang95** [comment]
I do able to save/load states with sd845 and 8GB ram. I am running with 2x resolution. However, the save state will crash at either saving/loading if i overwrite the same state too many times. I need to use a new state slot every ~5 overwrites. Then, i need to go to the folder to manually remove the state file since there is no option to remove the state file in the UI/menu.

**Comment by usernamaewa** [comment]
I had some troubles even on 2x res however that was with xbrz, now I'm fine even on 4x res not crashing with save states if only citra open, xbrz ram requirements just explodes even with 2x res and that was with rune factory 4 lol. Xbrz also causes missing textures on games it need fixes.

**Comment by Collosalhavoc** [comment]
So basically what we need to do is:
•Make sure lot of ram is available
•No other applications running in the background
•Disable texture filters(if any)
•Playing game at lower resolution

**Comment by Collosalhavoc** [comment]
P.S.
If game crashes while saving the same state too much times, going to file manager locating the citra-emu save state folder and deleting it might help


Thnx usernamaewa and luckywang95 for the suggestions
