### ISSUE TITLE
Game data loss when putting the application in the background

### ISSUE THREAD

**Issue by jknut** [citra-emu/citra-android#65]
When Citra has been minimized, sometimes the game is unloaded and has to be started over. Progress can be lost. 

Perhaps, running Citra as a service or with persistent notification will help prevent Android from closing

**Comment by SutandoTsukai181** [comment]
This is a limitation in Android itself, as the system is allowed to kill an app when low on memory. This may also happen even if a service is running, but it will be much less often. 

IMO a sure way to avoid this issue is to create emulation save states on activity exit and restore them whenever the app is reopened. This will avoid having the app running in memory for too long, which would get it killed.

Since save states are not implemented yet, I will just make it run a foreground service for the notification to stay permanent until emulation is closed or app is manually cleared from memory.
